完善功能

diff --git a/root/usr/bin/network-check b/root/usr/bin/network-check
--- a/root/usr/bin/network-check
+++ b/root/usr/bin/network-check
@@ -1,30 +1,36 @@
 #!/bin/sh
 
-INTERFACE="wan"
-TEST_HOST="8.8.8.8"
-MAX_FAILS=3
+CONFIG_FILE="/etc/config/network-manager"
+INTERFACE=$(uci -q get $CONFIG_FILE.basic.main.interface)
+TEST_HOST=$(uci -q get $CONFIG_FILE.advanced.settings.ping_host)
+MAX_FAILS=$(uci -q get $CONFIG_FILE.advanced.settings.retry)
+PING_INTERVAL=1
+PING_TIMEOUT=1
+FAILURE_WAIT=60
+
+logger -t NetworkManager[监测器] "服务启动：接口=$INTERFACE, 检测主机=$TEST_HOST"
 
 while true; do
     fails=0
     
-    # 检测网络状态
     for i in $(seq 1 $MAX_FAILS); do
-        if ! ping -c 1 -W 5 $TEST_HOST > /dev/null 2>&1; then
+        if ! ping -c 1 -W $PING_TIMEOUT $TEST_HOST >/dev/null 2>&1; then
             fails=$((fails+1))
+            logger -t NetworkManager[监测器] "网络异常 ($i/$MAX_FAILS)"
+            sleep $PING_INTERVAL
         else
             fails=0
             break
         fi
-        sleep 5
     done
 
     if [ $fails -ge $MAX_FAILS ]; then
-        logger -t NetworkManager "检测到网络断开，正在重启接口..."
+        logger -t NetworkManager[监测器] "触发重启：累计失败$MAX_FAILS次"
         ifdown $INTERFACE
-        sleep 5
+        sleep 2
         ifup $INTERFACE
-        logger -t NetworkManager "接口已重启，等待60秒后重新检测"
-        sleep 60
+        logger -t NetworkManager[监测器] "重启完成，冷却时间${FAILURE_WAIT}秒"
+        sleep $FAILURE_WAIT
     else
         sleep 30
     fi
